apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gd-ms-mysql-claim
spec:
  storageClassName: gd-ms-mysql-claim
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
