apiVersion: v1
kind: Service
metadata:
  name: gd-ms-redis
spec:
  selector:
    app: gd-ms-redis
  ports:
    - protocol: TCP
      port: 26379
      targetPort: 6379
      nodePort: 30002
  type: NodePort
  