apiVersion: apps/v1
kind: Deployment
metadata:
  name: gd-ms-user
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gd-ms-user
  template:
    metadata:
      labels:
        app: gd-ms-user
    spec:
      containers:
        - name: gd-ms-user
          image: gd-ms-user:v0.0.1
          ports:
            - containerPort: 8080

