apiVersion: v1
kind: Service
metadata:
  name: gd-ms-mysql
spec:
  selector:
    app: gd-ms-mysql
  ports:
    - protocol: TCP
      port: 23306
      targetPort: 3306
      nodePort: 30001
  type: NodePort
  