apiVersion: apps/v1
kind: Deployment
metadata:
  name: gd-ms-mysql
  labels:
    app: gd-ms-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gd-ms-mysql
  template:
    metadata:
      name: gd-ms-mysql
      labels:
        app: gd-ms-mysql
    spec:
      containers:
        - name: gd-ms-mysql
          image: mysql:8.0
          imagePullPolicy: IfNotPresent
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "root"
          ports:
            - containerPort: 3306
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: gd-ms-mysql-storage
      restartPolicy: Always
      volumes:
        - name: gd-ms-mysql-storage
          persistentVolumeClaim:
            claimName: gd-ms-mysql-claim
      