// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/gin-gonic/gin"
	"microservicedemo/internal/repo"
	"microservicedemo/internal/repo/dao"
	"microservicedemo/internal/service"
	"microservicedemo/internal/web"
	"microservicedemo/ioc"
)

// Injectors from wire.go:

func InitServer() *gin.Engine {
	db := ioc.InitGorm()
	userDao := dao.NewUserDao(db)
	userRepo := repo.NewUserRepo(userDao)
	userService := service.NewUserService(userRepo)
	userHandler := web.NewUserHandler(userService)
	engine := ioc.InitWebServer(userHandler)
	return engine
}
